name: Complexity check
on: [push, pull_request]

jobs:
  ccn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    
    
    - name : Install lizard
      run: pip install lizard
      
    - name: Limit complexity
      run: $HOME/.local/bin/lizard --exclude "./test/*" --CCN 5
